[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solana-fcg-tool"
version = "1.0.3"
description = "A comprehensive Rust project analyzer for Solana development with multi-platform support"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Solana Analyzer Team"},
]
maintainers = [
    {name = "Solana Analyzer Team"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Rust",
]
keywords = ["rust", "analyzer", "solana", "blockchain", "code-analysis"]
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "black",
    "flake8",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/your-repo/solana-analyzer"
Repository = "https://github.com/your-repo/solana-analyzer.git"
Issues = "https://github.com/your-repo/solana-analyzer/issues"

[project.scripts]
solana-fcg-tool = "solana_fcg_tool.cli:main"

[tool.setuptools]
packages = ["solana_fcg_tool"]
include-package-data = true

[tool.setuptools.package-data]
solana_fcg_tool = ["bin/*", "output/structures.rs", "*.md"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true